name: "dyff"
version: "0.1.7"
usage: "better diff for helm resource mainfests"
description: "better diff for helm resource mainfests"
command: "$HELM_PLUGIN_DIR/bin/dyff"
hooks:
  install: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
