name: "dyff"
version: "0.2.0"
usage: "helm dyff upgrade [flags] <release> <chart>"
description: "dyff between the current release and new one with a new chart version and values."
command: "$HELM_PLUGIN_DIR/bin/dyff"
hooks:
  install: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
